#########################################
#         user management system        #
#########################################

########         UserAPI        #########
### create new user
POST http://localhost:7070/useres
Content-Type: application/json

{
    "email":"hello@email.com",
    "name":"hello",
    "password":"123",
    "phone": "123",
    "bio":"I'm hello"
}


### get user by Id
GET http://localhost:7070/useres/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvQGVtYWlsLmNvbSIsImV4cCI6MTYxNjY5NjkwMiwiaWQiOjIsIm5hbWUiOiJoZWxsbyJ9.Sgi338FFwTCfSGcWakE2UOJn4-xWezy0qlwlLXB6mLQ
user-id: 2

########    AuthorizationAPI    #########
### get token based on email and password
POST http://localhost:7070/auths/jwt-token
Content-Type: application/json

{
    "email":"hello@email.com", "password":"123"
}

### check token is valid
GET http://localhost:7070/auths/isvalid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvQGVtYWlsLmNvbSIsImV4cCI6MTYxNjY5NjkwMiwiaWQiOjIsIm5hbWUiOiJoZWxsbyJ9.Sgi338FFwTCfSGcWakE2UOJn4-xWezy0qlwlLXB6mLQ
user-id: 2


### renew the token based on last valid token
GET http://localhost:7070/auths/renew
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvQGVtYWlsLmNvbSIsImV4cCI6MTYxNjY5NjkwMiwiaWQiOjIsIm5hbWUiOiJoZWxsbyJ9.Sgi338FFwTCfSGcWakE2UOJn4-xWezy0qlwlLXB6mLQ
user-id: 2
